version: '3.7'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=giftiglobal_user
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=giftiglobal_db

volumes:
  postgres_data:
